# Generated by Django 5.0.2 on 2024-02-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='date',
            field=models.DateField(),
        ),
    ]
