# Generated by Django 5.0.2 on 2024-02-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_socialmedia_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
